### ISSUE TITLE
Pipe results of tape to tap-spec, what about console logs?

### ISSUE THREAD

**Issue by besarthoxhaj** [foundersandcoders/clerk#9]
By running `npm test` looks like I lose the stout of the console logs. Is there some way to get it back? Or maybe I'm the only one encountering it?

However by running simpy `tape ./test/*.test.js` I get all the outputs from the console logs.

**Comment by MIJOTHY** [comment]
You can do `t.comment("hello m8")` instead of console logs.

**Comment by besarthoxhaj** [comment]
Thanks man thats cool! Will give it a go!;)
